### ISSUE TITLE
Favourite/star button not woring

### ISSUE THREAD

**Issue by shuvashish76** [slowscript/warpinator-android#102]
![Screenshot_2022-04-29-04-07-03](https://user-images.githubusercontent.com/48226312/165860068-ac05f7f2-8b8f-4fd2-a898-71ba1a2bd6c3.jpeg)

App version: 1.4.4 (1044) [F-Droid]
Android version: 8.1.0

**Comment by slowscript** [comment]
Fixed in 8ad4d456ae698bb9f13f7bf55a7db63dd3ee8809
