### ISSUE TITLE
v 1.5.2. File transfer from phone to computer stopped working

### ISSUE THREAD

**Issue by mastezont** [slowscript/warpinator-android#115]
After updating the Warpinator app on my phone from Android 8.1 to version 1.5.2, transferring files from the phone to a computer running Linux Mint 20.3, Warpinator version 1.2.9, stopped working.
I open any document or file on my phone, select "Share" via Warpinator, go to the GUI, where I confirm sending the file and am returned to this document or file. The file is not being sent. No Warpinator file acceptance request windows appear on the computer. In the /var/log/ufw.log of the computer, an entry appears stating that the connection from the ip phone to the ip of the computer is allowed.

**Comment by slowscript** [comment]
I think your problem could be internally the same thing as here: #114. Could you please test if the APK I've attached there fixes it?

**Comment by mastezont** [comment]
> Could you please test if the APK I've attached there fixes it?

I will now install this apk, check its work and write about the result.

**Comment by mastezont** [comment]
This version worked on transferring files from android to computer the first time. All attempts were successful.
Thanks for the quick fix!
