### ISSUE TITLE
Default download folder name mismatch

### ISSUE THREAD

**Issue by SZemanek** [slowscript/warpinator-android#118]
I noticed a little issue using this android app to transfer some files between android devices.  

The default folder is /storage/emulated/0/Download/Warpinator 

However, I think the default "Download" folder in Android should be "Downloads" (plural) 

and what is weird is it's creating a "Warpinator" folder in both the "/storage/emulated/0/Download/Warpinator" and built in Android "Downloads" folder.  However, if I send a file from one device to an Android phone, the file will appear in "/storage/emulated/0/Download/Warpinator" but not the built in Android "Downloads/Warpinator" folder.  

(Note:  This app was installed from the Google Play Store,  v.1.5.3)

**Comment by slowscript** [comment]
The download folder is a subfolder of whatever is in the `DIRECTORY_DOWNLOADS` environment variable. According to its [documentation](https://developer.android.com/reference/android/os/Environment#DIRECTORY_DOWNLOADS), the actual folder name is "Download" (singular, apparently for backwards compatibility) and it matches what I've seen on all devices I own. If your device has "Downloads", that is probably specific to your device's vendor.

However, I have no idea why it created a folder in "Downloads" also. Does it reappear if you delete it?

**Comment by SZemanek** [comment]
I guess I'll retract this bug report.   I think the issue might have been because of a weird  filetype filter UI glitch in the built in "com.android.documentsui" app that was making the folder appear empty.   I should probably find a better file manager app.  It does indeed appear now that Download and Downloads are linked. 

This was a new phone (GrapheneOS) that I wasn't used to yet, the UI was a little confusing.

**Comment by SZemanek** [comment]
I guess I'll retract this bug report. I think the issue might have been because of a weird filetype filter UI glitch in the built in "com.android.documentsui" app that was making the folder appear empty. I should probably find a better file manager app. It does indeed appear now that Download and Downloads are linked.

This was a new phone (GrapheneOS) that I wasn't used to yet, the UI was a little confusing.
