### ISSUE TITLE
Auto accept files

### ISSUE THREAD

**Issue by StickyDigit** [slowscript/warpinator-android#16]
More a feature request than an actual bug...
Please add an 'auto accept' button in settings. Having to accept each individual file is not Granny friendly.
Thanks.

**Comment by rares45** [comment]
Are you sure you would actually use it?

**Comment by StickyDigit** [comment]
It's available in the desktop app, where you can also opt to set it to prompt if an overwrite might happen.
Re safety: don't forget, the file received can only go into the directory set/created in settings, and if you don't run the app then nothing will happen at all. There are very few cases where I'd set the app to run automatically, but several where I'd want it to accept all files while running. Only devices on the local subnets with the same group name can send files.
Yes... I'd use it of course. Plonking several files from my laptop to my phone without having to keep poking the phone, or dropping a few pictures to my GF's phone. The overwrite option is handy in one case where I actually want to overwrite a status file on a remote system.

**Comment by rares45** [comment]
Then I will start working on it

**Comment by StickyDigit** [comment]
Nice one! Thank you. Warpinator (for both droid and linuxmint) just got properly useful :)
