### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by StickyDigit** [slowscript/warpinator-android#18]
I'm attempting to build in an admittedly hastily installed SDK to sanity check the auto-accept feature you just added (thanks!!!)
These cause "./gradlew build" to abort, requiring lint override in app/build.gradle.

connection_error; is not translated in ';de'; (German) or ';pt'; (Portuguese)
not_connected_to_wifi; is not translated in ';de'; (German) or ';pt'; (Portuguese)
accept_settings_title'; is not translated in ';cs'; (Czech), ';de'; (German), ';pt'; (Portuguese)
accept_setting_summary_on'; is not translated in ';cs'; (Czech), ';de'; (German), ';pt'; (Portuguese)
accept_setting_summary_off'; is not translated in ';cs'; (Czech), ';de'; (German), ';pt'; (Portuguese)
error_download_dir'; is not translated in ';de'; (German) or ';pt'; (Portuguese)

**Comment by rares45** [comment]
I have no idea why that happens (maybe you installed an old version of Gradle), but in `build.gradle` add these lines:
```
android {
     lintOptions {
        disable 'MissingTranslation'
    }
}
```
These should fix it. If not just wait for official builds on Google Play.

**Comment by rares45** [comment]
What version of Gradle you installed?

**Comment by rares45** [comment]
Actually instead of `./gradlew build` use `./gradlew :app:assembleRelease`

**Comment by rares45** [comment]
Did it work?

**Comment by StickyDigit** [comment]
Yes. Thank you.
./gradlew :app:assembleRelease
Just checked with a fresh git clone. Final tree was 100M smaller too :)
128M    warpinator-android
240M    warpinator-android--last
