### ISSUE TITLE
Allow Overwriting option not functioning

### ISSUE THREAD

**Issue by StickyDigit** [slowscript/warpinator-android#19]
The overwrite behaviour seems not to be affected by the "Allow Overwriting" option.

If 1.txt exists, and you send it again (same or modified), it will create 1(1).txt 1(2).txt etc.
Copying a directory twice creates duplicate files in the directory rather than a duplicate directory.

**Comment by slowscript** [comment]
Hmm.. overwriting works for me just fine. Didn't even have to restart the application after changing the setting. Could you double-check this? If the issue persists maybe a log would be helpful.

About directories, I think this is the desired behavior. When you copy a directory with any file manager, it tries to merge the directories.

**Comment by StickyDigit** [comment]
I agree largely about directories, though most FMs I've used will ask, so I've not often/ever allowed that to happen. Usually I'd either cancel and copy to new-dir-name, or if I'd intended a merge would allow overwrite 'if newer' or 'size differs',  so the dupes never occurred for me. The only place I've been aware of this (1) (2) thing is web browsers download where it's only ever single files, I always hated that they didn't warn about it, especially when inadvertantly re-downloading a large file on a small host.

I couldn't get a single overwrite yesterday  from laptop (mint 20.1) to rel 1.0.2 on Android 11, or to trunk on Android 7 (both lineage, no gapps)... Will recheck across a few more I have it installed on, see if I can narrow it down, and let you know. I confess I didn't try quitting and reloading the app. Will be more thorough this time.


On 27 March 2021 09:16:09 GMT, slowscript ***@***.***> wrote:
>Hmm.. overwriting works for me just fine. Didn't even have to restart the application after changing the setting. Could you double-check this? If the issue persists maybe a log would be helpful.
>
>About directories, I think this is the desired behavior. When you copy a directory with any file manager, it tries to merge the directories.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/slowscript/warpinator-android/issues/19#issuecomment-808698336
-- 
Sent from a phone. Please excuse my brevity.

**Comment by StickyDigit** [comment]
Ah.. Whoops! Sorry about this. I'd had a brain-fart by not using SAF path in my FM and wasn't actually deleting the files between tests. Took me a while to figure it out.
PICNIC !
I checked again with files and directories. From LinuxMint 20.1 to Android 7,9,10,11, all LineageOS. The 9 has Gapps too. All absolutely fine.
Closing.
