### ISSUE TITLE
UI: Download path query is confusing and unnecessary

### ISSUE THREAD

**Issue by clefebvre** [slowscript/warpinator-android#22]
Hi @slowscript,

First of all, many thanks for working on this. This is really cool, people are going to absolutely love it :) If you don't mind I'll cover the news on this in this month's blog post. I'm delighted to see this project.

**Bug description**

When you first run the app and no save directory is selected, the app shows a dialog. After you read the dialog and press `OK`, you're shown the `Downloads` screen, which is empty and has no item. Since it's the first time you use the app, you're not used yet to see your download items here, you don't know where to go to select your download directory and you're confused as to why your internal storage doesn't appear here. The buger menu -> Show internal storage obvious goal is for something different, but it adds to that confusion.

It's not obvious to a new user that the left menu should be used and an a storage device selected there before the directory can be selected.

**Suggested solution 1**

The easiest solution should be to direct the user to the root of the internal storage device after he/she presses OK rather to to the Downloads screen.

**Suggested solution 2**

Even better in my opinion. The app should work out of the box and not ask the user questions it doesn't absolutely need answered. Prefs are there for people to enjoy and tune, but going through mandatory choices should be restricted to absolute necessity. The same way you can change the username but you don't have to choose one before enjoying the app, you should be able to change the downloads directory, but the app would be more comfortable if it had a default value (/Download for instance) rather than asking the user.

**Comment by StickyDigit** [comment]
My 2p on that... The user needs to set a groupname, and be at least informed of where the files would go.

$sd/Download dir as default has some implications, potential clashes with browser downloads etc.

"Accept defaults", could perhaps be along the lines of  "group:EditMe, dir:$sd/Warpinator".

Only the group needs to be editable at the info screen. This is assuming the default dir is ONLY created when a file is first accepted so as not to leave an unwanted directory for the savvy user to have to clean up. 

Changing the default dir in prefs should still cause the users interaction with the file selector to cause its creation if not already existent.

So... Then the user gets an intro with clues about groups and default download directory, an easy way to set the group, and a big. button for GO, with maybe a small button for 'edit prefs' would be handy for those setting up a bunch of devices (as I did).

IMHO, the above would be least effort/impact/risk, user experience simplification for both savvy and simple users.

**Comment by slowscript** [comment]
Hi,
I'm glad to hear you like my work! Warpinator is an amazing tool and I'm happy I can help by making an Android port :)

For now I'll go with solution 1 (c24208f). The only problem is that the required API is not available on Android versions older than Oreo.

I agree that it would be better to use some default directory first but in this case I'm limited by the storage API I decided to use. The traditional way of accessing files is no longer permitted in Android 11 and up so I went with the Storage Access Framework. It allows me to use a custom directory but I need the user to give me explicit permission to access it (via the system directory picker).

I could also use the Media Store API to save directly to Downloads without any permission but I would not be able to give the user the choice to select any other location. In the end it will probably be necessary to combine both approaches which is something I plan to do eventually.

**Comment by StickyDigit** [comment]
As android version must (for reasons I don't care to delve into) be >=5 already, SAF ,which has been around since 4.4, clearly makes sense.

What will limit to >8 (Oreo) now, or have I misunderstood what you just said?

...my android 7's are gettin' scared :-O

**Comment by slowscript** [comment]
Don't worry, it's just that one specific feature that requires Android 8. Versions above that will now open the directory picker in the root directory of primary storage, versions below keep the default behavior :)

**Comment by StickyDigit** [comment]
Cushty!
-- 
Sent from a phone. Please excuse my brevity.

**Comment by slowscript** [comment]
The initial "Select download directory" prompt is now (since 1.4.3) avoided by having separate download logic for the default directory (Internal Storage/Download/Warpinator). Not the prettiest solution but the simplest I could think of that still works across all supported Android versions. Android <11 uses the WRITE_EXTERNAL_STORAGE permission, Android 11 & 12 seem to be able to store files in the Download directory without it. I have not found whether the 11&12 behavior is intentional so might have to redo this if it is just a bug that will be fixed.
