### ISSUE TITLE
Custom profile pictures fail on Android 11

### ISSUE THREAD

**Issue by StickyDigit** [slowscript/warpinator-android#24]
Only me again :)

This works on Android 10, and fails on Android 11.

Exported a 320x320 png file from Gimp as 8 bit RGB. Warped it to the target. Moved it to Pictures.
Opened prefs and selected custom image. From the file picker it was visible, and once selected the app drops me back to prefs, rather than profile pictures.. returning to profile pictures it showed the previously selected standard icon rather than my custom image.

I've attached the image.

![S4_mini-320a](https://user-images.githubusercontent.com/30390101/115150888-3a487b80-a062-11eb-90b6-9a351b00be21.png)

**Comment by slowscript** [comment]
I hate the way Android handles file permissions... I forgot to take persistable permission for the picture when it is selected and apparently older versions didn't care. Should be fixed now.

**Comment by StickyDigit** [comment]
Built. Tested. Working. Thanks!
