### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by jondo** [slowscript/warpinator-android#26]
Let me please suggest to release this on F-Droid.
(https://github.com/slowscript/warpinator-android/issues/11#issuecomment-776219398 says that it's already in there, but I can't find it, neither in the App nor on the F-Droid webpage.)

And then please put a link to its F-Droid page to the README.

**Comment by StickyDigit** [comment]
It'll appear in your F-Droid if you add the IzzyOnDroid repository.
See https://apt.izzysoft.de/fdroid/ for the repo details.
Note that the readme.md shows it as Play Store, and IzzyOnDroid, and provides links to both.

**Comment by jondo** [comment]
Would you agree to also have it in the official F-Droid repository? And does the app comply to the [inclusion policy](https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy)? If yes, I can create the corresponding [RFP request](https://f-droid.org/en/issues/).

**Comment by slowscript** [comment]
I don't know much about how normal F-Droid works. If you are able to submit it and it won't require any maintenance from my side, I have no problem with that. I've read through the inclusion policy and I think we should be fine.

**Comment by jondo** [comment]
Thank you! The RFP is now at https://gitlab.com/fdroid/rfp/-/issues/1723 .

**Comment by Hocuri** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8912 Should be on F-Droid in a week or so if all goes well :tada:

**Comment by slowscript** [comment]
Awesome! Glad to see it there.
