### ISSUE TITLE
localisation

### ISSUE THREAD

**Issue by ovari** [slowscript/warpinator-android#27]
How can this be translated into other languages?

Can you please add howto on the readme?

What do you think?

Thank you

**Comment by slowscript** [comment]
It can be translated just like any other Android application. Just copy strings.xml from `/app/src/main/res/values` to `/app/src/main/res/values-xx` where xx is the code of the language you are translating to. Then translate everything in the new xml file and submit a PR. I'm thinking about using some service that would make this easier. If I decide to do it I will definitely add instructions to the readme. For now however I don't think this is necessary.

**Comment by ovari** [comment]
Thank you for your comment. `hu (Hungarian - magyar) locale` https://github.com/slowscript/warpinator-android/pull/28 is ready for you.

Can we create a PR to add the following to your README.md:
>### Translations
>[Warpinator for Android](https://play.google.com/store/apps/details?id=slowscript.warpinator) can be translated just like any other Android application. Just copy `strings.xml` from `/app/src/main/res/values` to `/app/src/main/res/values-xx` where `xx` is the code of the language you are translating to. Then translate everything in the new xml file and submit a PR.

Hopefully you will get more translations for, and more installs of, your App as it was promoted in [Monthly News – April 2021](https://blog.linuxmint.com/?p=4054).

Thank you
