### ISSUE TITLE
Long username@hostname in available devices isn't shortened

### ISSUE THREAD

**Issue by AndreiMiculita** [slowscript/warpinator-android#32]
When the username@hostname in an item from the list of available devices is too long, it goes over the visibility toggle and gets cut off at the right edge of the purple box.

I think it should be either ellipsized or animated (so it moves right to left and back) in a smaller container.

**Comment by slowscript** [comment]
@rares45 If you are still around and have time, could you please look at this? It should be trivial to fix. Thanks!

**Comment by rares45** [comment]
I'll take care of it.
