### ISSUE TITLE
Only one way file movement working between Mint and Android

### ISSUE THREAD

**Issue by chrisaww** [slowscript/warpinator-android#38]
Installed flatpak implementation on Mint 4 May 21 and then Android version from Google store same day.
Noted that Mint version saw Android instance after it had been launched but Android did not see Mint instance.
Shutdown Android instance and restarted - this time it saw the Mint instance and connected to it.
I was able to drag a pdf file from Mint documents folder and it transferred to Android document folder - having set document folder as receiving directory.
BUT on 'sharing' a picture from Android gallery with Warpinator, the reverse file transfer although showing as being initiated timed out with no data movement.
Check that warpinator receiving directory had been created and it had the correct user write permissions.
Please advise next step.

**Comment by StickyDigit** [comment]
Check that the android Warpinator is version 1.2.
If it is 1.2, then check the desktop client is not set to "require approval before accepting files", else manually accept the file at that end else timeout will occur.

**Comment by slowscript** [comment]
Does desktop Warpinator see the transfer? If you run it from terminal with -d, does it print any errors? In mobile Warpinator, you can tap on a failed transfer and it will show some limited information about the error. If that is not enough, it would be great if you could obtain a log with ADB.

**Comment by chrisaww** [comment]
I have updated android version to 4 May release and can now say the file transfer works smoothly.
Thank you very much for your effort. It is really appreciated
