### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by heberjeur** [slowscript/warpinator-android#39]
Is it planned to have a Windows version in the near future?

**Comment by slowscript** [comment]
I would love to make one. Unfortunately I barely have enough time to manage this one, so maybe after the bugs here are sorted out.

**Comment by pervoj** [comment]
@slowscript I have some experience with Swing, so maybe I can help. It would be really nice to have clients for Warpinator on all platforms.

**Comment by slowscript** [comment]
I haven't heard of Swing up until now. If it were up to me I would use WinForms in .NET (looks more native and I like C# better) so I'm not sure whether you would want to work on that. Any help is welcome though. I think I may have time to start working on it in about 4 weeks or so. However if you are willing to make the Windows port yourself then go ahead. Worst case scenario is there will be two of them :smiley:

**Comment by pervoj** [comment]
Unfortunately, I can't program in C#. So I could help with either writing Java (Swing) or Vala (GTK). But none of that looks native on Windows.

Maybe I can make Czech translation.

**Comment by slowscript** [comment]
Sorry for not noticing the response earlier.

Again, if you want to, feel free to make your own version. Since Java is fairly portable maybe mac people could benefit from it too.

A český překlad myslím zvládnu sám :)

**Comment by slowscript** [comment]
Windows version now being developed here: https://github.com/slowscript/warpinator-windows. First release will be ready in a couple of weeks.
