### ISSUE TITLE
Remove `unofficial` from the title

### ISSUE THREAD

**Issue by ovari** [slowscript/warpinator-android#48]
This program has been promoted by @clefebvre at https://blog.linuxmint.com/?p=4054 with the blog stating:
> Today we’re delighted to announce that Warpinator is now also available for Android.

Since the official source announced your app, it doesn't seem `unofficial`. It seem more like the definitive and official source for Warpinator on Android.

Can `unofficial` please be removed from the title?

Having the unofficial label may make people wary of using your app.

What do you think?

Thank you

**Comment by slowscript** [comment]
I know they announced it but that doesn't change the fact that I'm not in any way affiliated with them. Technically I'm using their branding and I don't want my screw-ups to affect the perception of the Mint team in general. This is why I added the (unofficial) in the first place. If I were to remove it I think it would be best to get permission from someone on the team first.

Another thing is that they are also working on an official version (which will be released eventually) so it's probably a good idea to keep it to avoid confusion later on.
