### ISSUE TITLE
Added PC warpinator and broke android warpinators

### ISSUE THREAD

**Issue by strider222** [slowscript/warpinator-android#62]
I installed warpinator on my phone and tablet yesterday. They worked fine. Today I installed on ubuntu and it very quickly said no devices found. The android devices now say no devices found as well.

That the new install breaks the other installs implies that the issue is not a configuration error on the android devices.

**Comment by strider222** [comment]
So I restarted the phone app a few times. No luck. Then I watched TV with my wife for an hour. I left them alone not working. After watching a show, I picked up the phone all devices are now working. 

There must be a blocking message sent out by the PC as it starts.

**Comment by slowscript** [comment]
Do you get this behavior consistently? As in - no PC Warpinator and it works, once you start it it stops working? This seems very strange to me. I think your problem is similar to #61. Please see my response there.
