### ISSUE TITLE
Feature Request: Release on Amazon Store

### ISSUE THREAD

**Issue by ShneekeyTheLost** [slowscript/warpinator-android#63]
My wife owns a Kindle Fire, and apparently the Aurora Store won't download the Warpinator app, demanding it use Google Play. 

Could the app either be made compatible with the Aurora Store, or a release published on the Amazon Store so she doesn't have to jailbreak her tablet to use the app?

**Comment by EuKV** [comment]
Does Kindle Fire run Android? 
The minSDKVersion of Warpinator is "21" which is Android 5.0. What version of Android does your tablet have?
Cause I downloaded my Warpinator from the Aurora Store. I'm on Android 9.

**Comment by ShneekeyTheLost** [comment]
After further troubleshooting, the problem was Aurora Store, not Warpinator. Update to 4.0.7 fixed the issue with failing to download.
