### ISSUE TITLE
Service not running Network unavailable - try hotspot? Red banner

### ISSUE THREAD

**Issue by EuKV** [slowscript/warpinator-android#64]
Hi, the app works great for me transferring files both to the computer and between the phones. Thanks!
The issue I faced is the red banner with the message: "Service not running Network unavailable - try hotspot?" when press "Share" button from Gallery app or from file manager and then choose to share with Warpinator. The app window invokes with this banner though everything is working! Files are transferred to both computer and phones.
Is it possible to remove this banner when the app is invoked via the "Share" button from other apps?
Many thanks!

![Screenshot_20210710-003329_Warpinator](https://user-images.githubusercontent.com/85407169/125123970-32581f00-e119-11eb-93da-903fbe66ec99.png)

**Comment by slowscript** [comment]
Sorry for being away for so long. Your issue should now be fixed (it was trivial). I will return to working on the application in the next week or so and publish a new release which should contain the fix. Thanks for your patience.

**Comment by EuKV** [comment]
Thanks, looking forward to have a new release!
