### ISSUE TITLE
iOS Port

### ISSUE THREAD

**Issue by alex-tw-lam** [slowscript/warpinator-android#72]
Hi @slowscript , 

The app works like a charm. It's a really convenient solution for Android users. Just wondering can we port this app to iOS as well? 

Alex

**Comment by slowscript** [comment]
Hi Alex,

I'm pretty sure someone from the Linux Mint team is working on an iOS port already, although I'm not sure about the status.

If your question meant whether *you* (or anyone else) can make the port then sure, I never asked anyone when I made this one either :slightly_smiling_face: 

If your question meant whether *I* can make the port then the answer is no. I do not own any Apple devices so this is not something I could help with.
