### ISSUE TITLE
Errors during transfer

### ISSUE THREAD

**Issue by kiwilinux67** [slowscript/warpinator-android#73]
Hi, I am finding an issue where I cannot transfer any file from my PC to the android app. I can successfully transfer filers in the opposite direction. Attached is the log file from my phone. I am running the latest version of both apps (desktop 1.2.4, Android 1.3.2). Linux version is Opensuse Tumbleweed. 
I receive the transfer request to approve on the phone but as soon as the request is approved the error below appears. 

**Errors during transfer:**
Connection error: UNKNOWN:
Exception iterating responses:
'FileSender' object has no attribute 'current_mtime'

[latest.log](https://github.com/slowscript/warpinator-android/files/7071738/latest.log)

**Comment by slowscript** [comment]
Hi, you are probably using a not yet released version of the desktop application. When I download the latest source, I get the same error (introduced here: https://github.com/linuxmint/warpinator/commit/e9a14b53572dc8198a57d45b79a60440362de055). This happens every time so I'm sure someone will notice it before it is actually released. In the meantime try downgrading to an older version or install Warpinator from flatpak.

**Comment by TheBlueTroll** [comment]
I am additionally receiving this issue when trying to send a file from my pc to my phone.
works phone to pc
PC: Ubuntu 21.04, running warpinator 1.2.4
Android 1.3.2 from the play store.

additional notes: 
downgrading to warpinator 1.2.0 fixes it
warpinator 1.2.2 also works
warpinator 1.2.3 also works

while writing this slowscript posted his comment. and i see now that i installed from source (the recommended way for ubuntu 21 right now, sadly) and have ran into said issue. if i had instead done `git checkout 1.2.4` which is the current release i would have got a working version of warpinator on the pc. 
thank you for helping slow! please keep up the good work, the app is awesome!

**Comment by TheBlueTroll** [comment]
and now that mtwebster has commited a fix, the current source version of warpinator also works correctly now. ;)
