### ISSUE TITLE
App crashes on Google Pixel 5 running Android 12.

### ISSUE THREAD

**Issue by poldon** [slowscript/warpinator-android#81]
When I start the app, it starts to display the Download Directory message but crashes immediately before I can do anything.  I haven't been able to even use the app once so far.  I verified it had permissions for Files and Media also.

Here are all of the details I can think to give:

Android version: 12
Android Build Number: SP1A.211105.002.A1
Warpinator version: 1.4.1

Thanks for looking into this!

**Comment by slowscript** [comment]
It was an Android 12 specific issue I hope I have fixed just now. Please try version 1.4.2.

**Comment by poldon** [comment]
Yes, thank you!  Works now.
