### ISSUE TITLE
Google Tracking libraries

### ISSUE THREAD

**Issue by IzzySoft** [slowscript/warpinator-android#9]
It seems your app uses [Cloud Audit Logs](https://cloud.google.com/logging/docs/audit). Can you please clarify if

* that's active by default
* planned to be removed when "leaving beta"

For a tool intended to transfer files inside the local network, and especially a FOSS tool at that, using Google Tracking doesn't really look good :wink:

**Comment by slowscript** [comment]
I didn't know about this and I definitely didn't add it intentionally. I'm also not sure where you found that or what dependency is the problem. It could be something included by gRPC (which is a Google product). If you know how to get rid of it without breaking things, please let me know. I'm also not a huge fan of tracking :wink:

**Comment by IzzySoft** [comment]
I expected as much (I never trust any package starting with `com.android.google.` for exactly this reason: earlier or later they drag in nasty things). I found it via baksmali (using my own library scanner, based on Apktool – you can find details in my article [Identify modules in apps](https://android.izzysoft.de/articles/named/app-modules-2)). You could try running `gradle :app:dependencies` to find out what dragged it in. But not being an Android dev, I've no idea on how to "safely remove" it (except for replacing what caused it by something "purely FOSS").

Going over the other libraries detected (see the library section [on this page](https://apt.izzysoft.de/fdroid/index/apk/slowscript.warpinator)), I couldn't spot a high likely suspect. But the `gradle` command above should reveal it.

**Comment by slowscript** [comment]
It turns out that the tracking library was bundled in `com.google.api.grpc:proto-google-common-protos` which is not referenced anywhere and it is not included in the apk when minification is enabled. Now that it is removed your scanapk tool no longer complains.

**Comment by IzzySoft** [comment]
Yay, congrats! And good the solution was as easy as enabling minification (which should tell everyone it wasn't even used). But that Google starts dragging that in even with Proto! My, they meet my wildest fears in context with "avoid Google libs whenever possible because…".

Once you've made the next release, and my updater fetched that, it should yell at me to remove the "Tracking" flag (and I'll of course do so ASAP then). Feel free to "kick me" if that's not done within 2 days after your releasing (the "yell" happens when the update is published here, so removal of the flag will propagate with the next sync 1 day later usually).

Thanks for taking care! :smiley:
