### ISSUE TITLE
App not available in Play Store Latin America

### ISSUE THREAD

**Issue by geekyBoogiepop** [slowscript/warpinator-android#96]
The app is not available in my country (Latin America Region) on Play Store
![image](https://user-images.githubusercontent.com/32626891/162091917-49b30a92-e2a6-414a-be54-f6a8b286968b.png)

**Comment by slowscript** [comment]
When publishing the app, Google made me agree to comply with US regulation regarding export of encryption (or something like that, I'll look into it again). After reading what that means I found that there is a list of countries that are forbidden/restricted. I have disabled publishing in these countries out of caution. In Latin America those countries were Cuba, Nicaragua and Venezuela. I can no longer find Nicaragua on the list (or maybe I've excluded it by mistake) so I've enabled distribution there just now.

That being said, the app is still available on F-Droid (and here on GitHub).

If anyone knows whether this regulation actually applies to this app, let me know. I know there are some exceptions but I'm no expert in law. I simply don't want to get in trouble and have my developer account disabled.
