### ISSUE TITLE
Spanish locale update

### ISSUE THREAD

**Issue by c-sanchez** [slowscript/warpinator-android#97]
Hi, I've updated the spanish translation with the missing strings, I've also cut some things a little bit shorter so you can read them completely.
(At least in the case of my screen)
Always keeping the sense of each line so that it is equally understood.
spanish strings.xml attached as strings.txt
[strings.txt](https://github.com/slowscript/warpinator-android/files/8439583/strings.txt)

**Comment by slowscript** [comment]
Committed here: 91f322a4db5b6c36a38a9d68a91d8a6fee69a1c0
