### ISSUE TITLE
Flip order of transfer history, to match desktop client

### ISSUE THREAD

**Issue by AndreiMiculita** [slowscript/warpinator-android#98]
On the desktop client, the most recent transfers show on top. On the Android client, they're on the bottom.

For consistency, they should be ordered the same way.

The most recent transfers should also be the most easily visible, and the mobile client doesn't automatically scroll to the bottom of the transfer history, making them less accessible.

**Comment by slowscript** [comment]
Will do. I made the new transfers append to the end of the list because it was easier to do, but having consistency with the desktop version makes sense.
